import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Raleway } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const clashDisplay = localFont({
  src: './fonts/ClashDisplay-Variable.woff2',
  display: 'swap',
  variable: '--font-clash-display', 
})

const railway = Raleway({
  variable: "--font-railway",
  subsets: ["latin"],
  display: 'swap',
  weight: ['300', '400', '700'], 
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${clashDisplay.variable} ${lato.variable} ${railway.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
